services:
  cv:
    image: ghcr.io/mfrh89/mfrh-cv:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - cv-content:/app/content
    environment:
      - NODE_ENV=production
      - KEYSTATIC_STORAGE_KIND=local

volumes:
  cv-content:
